### ISSUE TITLE
Venom movie player broken

### ISSUE THREAD

**Issue by versus2** [a4k-openproject/json.openplayers#55]
While tvshows works ok movie player throws error

**Comment by drinfernoo** [comment]
Please attach a log file so we can see the error. This read like someone taking their car to the shop and telling the mechanic: "car no go".

**Comment by versus2** [comment]
[kodi.log](https://github.com/a4k-openproject/json.openplayers/files/6592942/kodi.log)

**Comment by drinfernoo** [comment]
The players were just updated. Try updating them and see if they work.

**Comment by 123Venom** [comment]
There's an issue best I can tell is with TMDb Helper.  Both Seren and Venom player cause TMDb Helper to freeze at the busy dialog attempting to scrape and then hard crash Kodi.  This only happens to me inside TMDb Helper trying to play movies and using either Venom or Seren's `Source Select` playback method.  Autoplay seems to be fine.  Epsisodes plays fine for me as well.  Also adding movies to the library the .strm files plays fine in all regards as well.  You might want to post an issue there.

Your log also has a key error for `rating` and that key request, `{rating}`,  from TMDB Helper was an old carry over from OpenMeta that was removed a few versions ago so your on a few version old player file that's causing that error.

**Comment by 123Venom** [comment]
Just did yet another player file update for Venom's `Source Select`.  The problem is `is_resolvable` needs to be set to True.  Both Seren and Venom are using False and this causes the crash.  The problem was not TMDb Helper so I was wrong once further debugging the issue.  The update should be available later today.

**Comment by versus2** [comment]
Still no luck (players updated from 51 to 54) with Venom ( both source select and auto) when playing movies. Both have is_resolvable set to True in TMDb Helper players config. Waiting for 123venom update.

[kodi.log](https://github.com/a4k-openproject/json.openplayers/files/6593968/kodi.log)

**Comment by versus2** [comment]
Now i see that I was using http://bit.ly/openplayers  as update URL  instead of http://bit.ly/tmdbplayers but unfortunately it made no difference. Still throwing error.

**Comment by 123Venom** [comment]
> 
> 
> Now i see that I was using http://bit.ly/openplayers as update URL instead of http://bit.ly/tmdbplayers but unfortunately it made no difference. Still throwing error.

if your log still has this error when you fixed your url

```
Error Type: <class 'KeyError'>
Error Contents: 'rating'
```

Then your local version is still outdated.  That error will ONLY throw if I ask TMDb Helper to return `{rating}` when it does not allow that key to be returned.  That key was removed from the Venom player.  Since changing the `is_resolvable` to `true` in both Venom and Seren both now play fine and I do not get that log error.

[kodi_venom.log](https://ufile.io/67ahqps3)

If you look at my log snip you'll see the path TMDb Helper retrieves from the player file, no error.  You'll also note the path is shown and works because `{rating}` key is not in it.  Now look at yours and you can see it takes a dump because it's seeing `{rating}` key being asked for that does not exist since last 2 versions.

**Comment by drinfernoo** [comment]
@versus2 The `openplayers` URL is players for OpenMeta. Use the correct link, update your players, and you'll be fine.

**Comment by drinfernoo** [comment]
The `openplayers` URL is for OpenMeta players. Use the correct link for TMDBHelper (`tmdbplayers`), update your players (there have been two fixes pushed *today*), and you'll be fine.
